version: '3.8'
services:
  model_api:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "5002:5002"


  gradio-app:
    build:
      context: .
      dockerfile: Dockerfile-interface
    ports:
      - "7860:7860"
    depends_on:
      - model_api