version: '3.8'
services:
  gradio-app:
    build:
      context: .
      dockerfile: Dockerfile-interface-test
    ports:
      - "7860:7860"
    depends_on:
      - model_api

  model_api:
    build:
      context: .
      dockerfile: Dockerfile-app-test
    ports:
      - "5002:5002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002"]
      interval: 10s
      timeout: 5s
      retries: 3
