version: '3.8'
services:
  gradio-app:
    build:
      context: .
      dockerfile: Dockerfile-interface 
    ports:
      - "7860:7860"  
    depends_on:
      - model_api 

  model_api:
    build:
      context: .
      dockerfile: Dockerfile-app  
    ports:
      - "5002:5002"  
