# Utiliser une image de base Python
FROM python:3.9-slim

# Copier les fichiers nécessaires dans l'image
COPY requirements.txt .
COPY Part_1/prediction_model.pth .
COPY Part_2/recommendation_model.pth .
COPY Part_1/model1.py .
COPY Part_2/model2.py .
COPY Part_2/movie_posters.ann .
COPY Part_3/bow_annoy.ann .
COPY Part_3/distilbert_annoy.ann .
COPY Part_2/poster_paths.txt .
COPY Part_3/bag_of_words_embeddings.pkl .
COPY Part_3/distilbert_embeddings.pkl .
COPY Part_3/movies_metadata.pkl .
COPY app.py .

# Installer les dépendances nécessaires à la compilation
RUN apt-get update && \
    apt-get install -y build-essential python3-dev gcc g++ make && \
    rm -rf /var/lib/apt/lists/*

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port pour l'API
EXPOSE 5002

# Démarrer l'API du modèle Annoy
CMD ["python", "app.py"]
