# Utiliser une image de base Python
FROM python:3.9-slim

# Copier les fichiers nécessaires dans l'image
COPY requirements.txt .
COPY interface.py .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port de l'application Gradio
EXPOSE 7860

# Démarrer l'application Gradio
CMD ["python", "interface.py"]

